# Generated by Django 5.0.3 on 2024-04-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_user_type_customerprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('customer', 'Customer')], max_length=30),
        ),
    ]
