# Generated by Django 5.0.3 on 2024-04-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('customer', 'Customer'), ('admin', 'Admin')], max_length=30),
        ),
    ]
