# Generated by Django 5.0.3 on 2024-04-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='restaurant_id',
        ),
    ]
