# Generated by Django 5.0.3 on 2024-04-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_customerprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='first_name',
            field=models.CharField(default='first name', max_length=255),
        ),
    ]
