# Generated by Django 5.0.3 on 2024-04-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customerprofile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='first_name',
            field=models.CharField(default='first name', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='last_name',
            field=models.CharField(default='last name', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='restaurant_name',
            field=models.CharField(default='Default Restaurant', max_length=30),
        ),
    ]
