# Generated by Django 5.0.3 on 2024-04-13 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customerprofile_restaurantprofile'),
        ('main', '0003_order_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='start_datetime',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='end_datetime',
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.restaurantprofile'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fooditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
