# Generated by Django 5.0.3 on 2024-04-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('request', 'Request'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='request', max_length=10),
        ),
    ]
