# Generated by Django 5.0.3 on 2024-04-14 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customerprofile_restaurantprofile'),
        ('main', '0006_remove_booking_created_at_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.restaurantprofile'),
        ),
    ]
